version: "2"

networks:
  idm_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.1.0/24
         gateway: 172.18.1.1

volumes:
  vol-mysql:

services:

  mysql:
    image: mysql/mysql-server:5.7.21
    ports:
      - "3306:3306"
    networks:
      idm_network:
        ipv4_address: 172.18.1.5
    environment:
      - MYSQL_ROOT_PASSWORD=idm
      - MYSQL_ROOT_HOST=172.18.1.6

  fiware-idm:
    image: fiware/idm:7.4.0
    ports:
      - "3000:3000"
      - "443:443"
    networks:
      idm_network:
        ipv4_address: 172.18.1.6
    environment:
      - DATABASE_HOST=172.18.1.5
    volumes:
      - ./fiware-idm/seeders:/opt/fiware-idm/seeders
    command:
      - npm run-script seed_db

  chocolate-factory:
    image: chocolatefactoryjwt
    ports:
      - "4000:4000"
    networks:
      idm_network:
        ipv4_address: 172.18.1.7

  candy-factory:
    image: candyfactoryjwt
    ports:
      - "5000:5000"
    networks:
      idm_network:
        ipv4_address: 172.18.1.8